/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.allaybotai;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.awt.*;

/**
 *
 * @author Ismael
 */
public class MenuBienvenida extends javax.swing.JFrame {
    
    
    
    public MenuBienvenida() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BttnSalir = new javax.swing.JButton();
        BttnCreditos = new javax.swing.JButton();
        BttnJugar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AllayQuest: ¡Busqueda de Tesoros!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 370, -1));

        BttnSalir.setBackground(new java.awt.Color(250, 162, 117));
        BttnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BttnSalir.setText("Salir");
        BttnSalir.setBorder(null);
        BttnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(BttnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 90, 30));

        BttnCreditos.setBackground(new java.awt.Color(198, 207, 187));
        BttnCreditos.setForeground(new java.awt.Color(0, 0, 0));
        BttnCreditos.setText("Creditos");
        BttnCreditos.setBorder(null);
        jPanel1.add(BttnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 90, 30));

        BttnJugar.setBackground(new java.awt.Color(231, 203, 152));
        BttnJugar.setForeground(new java.awt.Color(0, 0, 0));
        BttnJugar.setText("Jugar");
        BttnJugar.setBorder(null);
        BttnJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BttnJugarMouseClicked(evt);
            }
        });
        BttnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(BttnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Busqueda_resized.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BttnSalirMouseClicked

    private void BttnJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BttnJugarMouseClicked
        
    }//GEN-LAST:event_BttnJugarMouseClicked

    private void BttnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnJugarActionPerformed
        Juego juegote = new Juego();
        juegote.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BttnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnCreditos;
    private javax.swing.JButton BttnJugar;
    private javax.swing.JButton BttnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
